# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hadleigh Schwartz's Page
email: hadleigh@cs.columbia.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
domain: hadleigh-schwartz.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://hadleigh-schwartz.github.io  # the base hostname and protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

  # Content
content:

  ## Collaborator pages
  charlie: "<a href=\"https://www.cs.columbia.edu/~cjc/\">Charles Carver</a>"
  xia: "<a href=\"https://www.cs.columbia.edu/~xia/\">Xia Zhou</a>"
  dan: "<a href=\"https://www.cs.columbia.edu/~danr/\">Dan Rubenstein</a>" 
  vishal: "<a href=\"https://www.cs.columbia.edu/~misra/\">Vishal Misra</a>"  
  sam: "<a href=\"https://samuel-deng.github.io/\">Sam Deng</a>" 
  xiaofeng: "<a href=\"\">Xiaofeng Yan</a>"  
  qijia: "<a href=\"https://qijiashao.github.io/\">Qijia Shao</a>"  
  nicholas: "<a href=\"\">Nicholas Shade</a>"  
  joe: "<a href=\"\">Joseph Lazzaro</a>"  
  eric: "<a href=\"https://ericfossum.com/\">Eric Fossum</a>"  
  xiaoxin: "<a href=\"\">Xiaoxin Wang</a>"  
  jifeng: "<a href=\"https://faculty-directory.dartmouth.edu/jifeng-liu\">Jifeng Liu</a>"  
  brian: "<a href=\"https://brianplancher.com/\">Brian Plancher</a>"  
  vikram: "<a href=\"https://homes.cs.washington.edu/~vsiyer/\">Vikram Iyer</a>"  
  zach: "<a href=\"https://zachary.englhardt.com/\">Zachary Englhardt</a>"  
  toma: "<a href=\"https://www.tomaitagaki.com/\">Toma Itagaki</a>"  
  megan:  "<a href=\"\">Megan Graciela Nauli Manik</a>"  
  chun:  "<a href=\"\">Chun-Cheng Chang</a>"  
  kechen: "<a href=\"\">Kechen Liu</a>"  
  kelly:  "<a href=\"\">Kelly Yen</a>"  
  heather: "<a href=\"https://people.cs.uchicago.edu/~htzheng/\">Heather Zheng</a>" 
  sandlab: "<a href=\"https://sandlab.cs.uchicago.edu/\">SAND Lab</a>" 


  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
